name: Push Github Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch the theme and its submodules
          fetch-depth: 1  # the dependency of the themes have very long histories

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install      
        run: npm install

      - name: Build
        run: npm run build

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Geojson-Pydantic
        run: pip install geojson-pydantic==0.4.3

      - name: Add JSON schemas
        run: |
          git clone https://github.com/DGEXSolutions/osrd.git /tmp/osrd_repo
          mkdir public/schemas
          python /tmp/osrd_repo/api/osrd_infra/schemas/infra.py > public/schemas/infra_schema.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
